### ISSUE TITLE
 delay signed but not fully signed

### ISSUE THREAD

**Issue by joebetmutia** [invertedtomato/crc#16]
anyone also experiencing this?

Could not load file or assembly 'InvertedTomato.Crc' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by invertedtomato** [comment]
I haven't but feel free to remove the strong signing. It was a box-ticketing exercise to help some users of the package, however adds no value really.

**Comment by joebetmutia** [comment]
hi @invertedtomato yes i figured it out yesterday when i downloaded the full repo.. seems like i just needed to comment something out and create a build out of it..

its just weird that it doesnt work out of the box so i was startled 

all works afterwards.

and awesome library thank you
