### ISSUE TITLE
Missing tags in git repo

### ISSUE THREAD

**Issue by maettu-this** [invertedtomato/crc#4]
Hi Ben,

I've come across your pretty clean and extensive CRC library, looking for something just like this for https://sourceforge.net/projects/y-a-terminal/, for adding e.g. [Modbus capabilities](https://sourceforge.net/p/y-a-terminal/feature-requests/300/).

Nugetting releases is fine. But sometimes, for debugging, I like to see the related source code. Unfortunately, your git repo doesn't show any tags that correspond to the releases, neither are github releases available. Consequently, looking at today's code, I cannot see whether or not this is the code running in version 1.3.0 of the library.

Could this be improved for future releases? And could you tag the last 1.3.0 release?

Best regards,
Matthias

**Comment by invertedtomato** [comment]
Sure thing, and thanks Matthias. It's about time I started using releases. https://github.com/invertedtomato/crc/releases/tag/v1.3.1
