### ISSUE TITLE
Missing .xml in NuGet package

### ISSUE THREAD

**Issue by maettu-this** [invertedtomato/crc#5]
Hi Ben

The package directories `\InvertedTomato.Crc.1.3.0\lib\*\` only contain the `InvertedTomato.Crc.dll`, but no accompanying `InvertedTomato.Crc.xml`. Please generate and deploy.

Best regards,
Matthias

**Comment by invertedtomato** [comment]
Sure thing. Is this what you mean? https://github.com/invertedtomato/crc/releases/tag/v1.3.3

**Comment by maettu-this** [comment]
Exactly, `\lib` now contains the `.xml`:

![grafik](https://github.com/invertedtomato/crc/assets/24897735/b2d552e2-4bf4-4bb6-8f31-9a7ea009d4c2)

However, the newly added `content` and `contentFiles` folders have an impact on a Visual Studio project, the `.xml` automatically gets shown, others (e.g. `IPNetwork`) don't show this:

![grafik](https://github.com/invertedtomato/crc/assets/24897735/22f83900-d840-49a2-992e-251c8f1f7a06)
